version: "2"

linters:
  enable:
    - goconst
    - gocritic
    - misspell
    - staticcheck
    - unconvert
    - unparam
    - gocheckcompilerdirectives

  settings:
    govet:
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    gocyclo:
      min-complexity: 10
    dupl:
      threshold: 100
    goconst:
      min-len: 5
      min-occurrences: 2
    misspell:
      locale: US
    lll:
      line-length: 140
    gocritic:
      enabled-tags:
        - performance
        - style
        - experimental
      disabled-checks:
        - wrapperFunc
    goheader:
      values:
        const:
          # Define here const type values in format k:v.
          # For example:
          COMPANY: KKRT Labs
          YEAR: "2024"
          PROJECT: Kakarot Go-Utils
          SPDX: Unlicense
      template: |-
        SPDX-License-Identifier: {{ SPDX }}
        (c) Copyright {{ YEAR }} {{ COMPANY }} all rights reserved.
        This file is part of the project {{ PROJECT }}.
  exclusions:
    paths:
      - .gocache
      - build
      - mock
      - deps
      - vendor
      - pkg/ethereum/trie # skip files forked from geth
      - pkg/ethereum/state/database_modified_trie.go

formatters:
  enable:
    - goimports
    - gofmt

  exclusions:
    paths:
      - .gocache
      - build
      - mock
      - deps
      - vendor
      - pkg/ethereum/trie # skip files forked from geth
      - pkg/ethereum/state/database_modified_trie.go

run:
  timeout: 20m
  
  
